version: '3.9'

services:
  tomcat:
    container_name: Tomcat-Server
    image: tomcat:9.0-jdk17-corretto
    ports:
    - "8088:8080"
    
    volumes:
     - /opt/docker/tomcat/webapps:/usr/local/tomcat/webapps
     - /opt/docker/tomcat/logs:/usr/local/tomcat/logs
    - /opt/docker/tomcat/temp:/opt/temp
    environment:
    - TZ=Pacific/Auckland

